/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JTextField;
import Control.Control;

/**
 *
 * @author unifvnobre
 */
public class Calculadora extends javax.swing.JFrame {

    public Calculadora() {
        initComponents();
        c = new Control(this);
    }

    public JButton getBtn_clear() {
        return Btn_clear;
    }

    public void setBtn_clear(JButton Btn_clear) {
        this.Btn_clear = Btn_clear;
    }

    public JButton getBtn_eight() {
        return Btn_eight;
    }

    public void setBtn_eight(JButton Btn_eight) {
        this.Btn_eight = Btn_eight;
    }

    public JButton getBtn_equals() {
        return Btn_equals;
    }

    public void setBtn_equals(JButton Btn_equals) {
        this.Btn_equals = Btn_equals;
    }

    public JButton getBtn_five() {
        return Btn_five;
    }

    public void setBtn_five(JButton Btn_five) {
        this.Btn_five = Btn_five;
    }

    public JButton getBtn_four() {
        return Btn_four;
    }

    public void setBtn_four(JButton Btn_four) {
        this.Btn_four = Btn_four;
    }

    public JButton getBtn_minus() {
        return Btn_minus;
    }

    public void setBtn_minus(JButton Btn_minus) {
        this.Btn_minus = Btn_minus;
    }

    public JButton getBtn_mult() {
        return Btn_mult;
    }

    public void setBtn_mult(JButton Btn_mult) {
        this.Btn_mult = Btn_mult;
    }

    public JButton getBtn_nine() {
        return Btn_nine;
    }

    public void setBtn_nine(JButton Btn_nine) {
        this.Btn_nine = Btn_nine;
    }

    public JButton getBtn_one() {
        return Btn_one;
    }

    public void setBtn_one(JButton Btn_one) {
        this.Btn_one = Btn_one;
    }

    public JButton getBtn_plus() {
        return Btn_plus;
    }

    public void setBtn_plus(JButton Btn_plus) {
        this.Btn_plus = Btn_plus;
    }

    public JButton getBtn_seven() {
        return Btn_seven;
    }

    public void setBtn_seven(JButton Btn_seven) {
        this.Btn_seven = Btn_seven;
    }

    public JButton getBtn_six() {
        return Btn_six;
    }

    public void setBtn_six(JButton Btn_six) {
        this.Btn_six = Btn_six;
    }

    public JButton getBtn_three() {
        return Btn_three;
    }

    public void setBtn_three(JButton Btn_three) {
        this.Btn_three = Btn_three;
    }

    public JButton getBtn_two() {
        return Btn_two;
    }

    public void setBtn_two(JButton Btn_two) {
        this.Btn_two = Btn_two;
    }

    public JButton getBtn_zero() {
        return Btn_zero;
    }

    public void setBtn_zero(JButton Btn_zero) {
        this.Btn_zero = Btn_zero;
    }

    public JTextField getTxt_resultado() {
        return Txt_resultado;
    }

    public void setTxt_resultado(JTextField Txt_resultado) {
        this.Txt_resultado = Txt_resultado;
    }

    public JButton getBtn_div() {
        return Btn_div;
    }

    public void setBtn_div(JButton btn_div) {
        this.Btn_div = btn_div;
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_resultado = new javax.swing.JTextField();
        Btn_seven = new javax.swing.JButton();
        Btn_eight = new javax.swing.JButton();
        Btn_nine = new javax.swing.JButton();
        Btn_div = new javax.swing.JButton();
        Btn_mult = new javax.swing.JButton();
        Btn_four = new javax.swing.JButton();
        Btn_five = new javax.swing.JButton();
        Btn_six = new javax.swing.JButton();
        Btn_minus = new javax.swing.JButton();
        Btn_one = new javax.swing.JButton();
        Btn_two = new javax.swing.JButton();
        Btn_three = new javax.swing.JButton();
        Btn_plus = new javax.swing.JButton();
        Btn_clear = new javax.swing.JButton();
        Btn_zero = new javax.swing.JButton();
        Btn_equals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Txt_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_resultadoActionPerformed(evt);
            }
        });

        Btn_seven.setText("7");
        Btn_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sevenActionPerformed(evt);
            }
        });

        Btn_eight.setText("8");
        Btn_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eightActionPerformed(evt);
            }
        });

        Btn_nine.setText("9");
        Btn_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_nineActionPerformed(evt);
            }
        });

        Btn_div.setText("/");
        Btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_divActionPerformed(evt);
            }
        });

        Btn_mult.setText("X");
        Btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_multActionPerformed(evt);
            }
        });

        Btn_four.setText("4");
        Btn_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_fourActionPerformed(evt);
            }
        });

        Btn_five.setText("5");
        Btn_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_fiveActionPerformed(evt);
            }
        });

        Btn_six.setText("6");
        Btn_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sixActionPerformed(evt);
            }
        });

        Btn_minus.setText("-");
        Btn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_minusActionPerformed(evt);
            }
        });

        Btn_one.setText("1");
        Btn_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_oneActionPerformed(evt);
            }
        });

        Btn_two.setText("2");
        Btn_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_twoActionPerformed(evt);
            }
        });

        Btn_three.setText("3");
        Btn_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_threeActionPerformed(evt);
            }
        });

        Btn_plus.setText("+");
        Btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_plusActionPerformed(evt);
            }
        });

        Btn_clear.setText("C");
        Btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_clearActionPerformed(evt);
            }
        });

        Btn_zero.setText("0");
        Btn_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_zeroActionPerformed(evt);
            }
        });

        Btn_equals.setText("=");
        Btn_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_equalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_resultadoActionPerformed
        
    }//GEN-LAST:event_Txt_resultadoActionPerformed

    private void Btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_clearActionPerformed
        c.controlClear();
    }//GEN-LAST:event_Btn_clearActionPerformed

    private void Btn_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_oneActionPerformed
        c.concatenarNumeros("1");
    }//GEN-LAST:event_Btn_oneActionPerformed

    private void Btn_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_twoActionPerformed
        c.concatenarNumeros("2");
    }//GEN-LAST:event_Btn_twoActionPerformed

    private void Btn_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_zeroActionPerformed
        c.concatenarNumeros("0");
    }//GEN-LAST:event_Btn_zeroActionPerformed

    private void Btn_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_threeActionPerformed
        c.concatenarNumeros("3");
    }//GEN-LAST:event_Btn_threeActionPerformed

    private void Btn_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_fourActionPerformed
        c.concatenarNumeros("4");
    }//GEN-LAST:event_Btn_fourActionPerformed

    private void Btn_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_fiveActionPerformed
        c.concatenarNumeros("5");
    }//GEN-LAST:event_Btn_fiveActionPerformed

    private void Btn_nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_nineActionPerformed
        c.concatenarNumeros("9");
    }//GEN-LAST:event_Btn_nineActionPerformed

    private void Btn_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sixActionPerformed
        c.concatenarNumeros("6");
    }//GEN-LAST:event_Btn_sixActionPerformed

    private void Btn_eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eightActionPerformed
        c.concatenarNumeros("8");
    }//GEN-LAST:event_Btn_eightActionPerformed

    private void Btn_sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sevenActionPerformed
        c.concatenarNumeros("7");
    }//GEN-LAST:event_Btn_sevenActionPerformed

    private void Btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_divActionPerformed
        c.Div();
        c.controlClear();
    }//GEN-LAST:event_Btn_divActionPerformed

    private void Btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_multActionPerformed
        c.Mult();
        c.controlClear();
    }//GEN-LAST:event_Btn_multActionPerformed

    private void Btn_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_minusActionPerformed
        c.Subtracao();
        c.controlClear();
    }//GEN-LAST:event_Btn_minusActionPerformed

    private void Btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_plusActionPerformed
        c.Soma();
        c.controlClear();
    }//GEN-LAST:event_Btn_plusActionPerformed

    private void Btn_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_equalsActionPerformed
        c.controlEquals();
    }//GEN-LAST:event_Btn_equalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    private Control c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_clear;
    private javax.swing.JButton Btn_div;
    private javax.swing.JButton Btn_eight;
    private javax.swing.JButton Btn_equals;
    private javax.swing.JButton Btn_five;
    private javax.swing.JButton Btn_four;
    private javax.swing.JButton Btn_minus;
    private javax.swing.JButton Btn_mult;
    private javax.swing.JButton Btn_nine;
    private javax.swing.JButton Btn_one;
    private javax.swing.JButton Btn_plus;
    private javax.swing.JButton Btn_seven;
    private javax.swing.JButton Btn_six;
    private javax.swing.JButton Btn_three;
    private javax.swing.JButton Btn_two;
    private javax.swing.JButton Btn_zero;
    private javax.swing.JTextField Txt_resultado;
    // End of variables declaration//GEN-END:variables

}
